### ISSUE TITLE
support for AsciiDoc(tor)/reS formats

### ISSUE THREAD

**Issue by gour** [masasam/emacs-easy-hugo#12]
Hello,

thank you for very interesting package!

Considering I plan to use AsciiDoc(tor) markup with Hugo, what do you think to extend the package by adding support for AsciiDoc(tor)/reST markup formats?

**Comment by masasam** [comment]
Hi gour.
Thank you for an interesting proposal.
I didn't know AsciiDoc(tor)/reST.
I will add support for AsciiDoc(tor)/reST markup formats.

**Comment by masasam** [comment]
Hi @gour .
Added support for AsciiDoc(tor)/reST markup formats, so try using it.
Please report if there is a problem.

**Comment by gour** [comment]
@masasam Thank you very much for adding it!

> Please report if there is a problem.

There is one thing I can think of...adding ability to configure list of extensions for each markup, e.g. besides _*.ad_, the _*.adoc_ or _*.txt_ are common formats used for AsciiDoc(tor) files, similar with reST where _*.txt_ is quite common one, so my idea is that instead of depending just on hard-cored extensions, it would be nice to provide ability that user provides his/her own (a)list for each markup format by adding to the default extension and then the code should just iterate through the list while detecting correct format?

I'd gladly help, but, unfortunately, my current Elisp skills are inadequate although I hope to improve it in the future.

**Comment by masasam** [comment]
Hi @gour .
Added support for changing the extension of markdown and asciidoc,  so try using it.
Please select *.ad or *.asciidoc or *.adoc at extension.
Because only these three are supported by hugo.
*.txt is not support in hugo.
For example, write at your init.el ...
(setq easy-hugo-asciidoc-extension "asciidoc")

**Comment by gour** [comment]
@masasam 
What is wrong:

```
Debugger entered--Lisp error: (error "Please enter .md or .org or .adoc or .rst or .mmark or .html file name")
  signal(error ("Please enter .md or .org or .adoc or .rst or .mmark or .html file name"))
  error("Please enter .%s or .org or .%s or .rst or .mmark or .%s file name" "md" "adoc" "html")
  easy-hugo-newpost("test.adoc")
  funcall-interactively(easy-hugo-newpost "test.adoc")
  call-interactively(easy-hugo-newpost nil nil)
  command-execute(easy-hugo-newpost)
```
considering that I defined:

```
(setq easy-hugo-asciidoc-extension "adoc")
```
 in my _init.el_ and just wanted to create new _test.adoc_ file?

**Comment by masasam** [comment]
Are you using MELPA?
If you are using melpa, please tell me the version of line 7.
Package-Version: 20170425.520?

**Comment by masasam** [comment]
Hi @gour 
Are you using MELPA?
If you are using melpa, please tell me the version of line 7.
Package-Version: 20170425.520?

**Comment by masasam** [comment]
Please erase the test.ad file if it exists.
Since hugo can not distinguish between test.ad and test.adoc, it gets an error.
I will consider countermeasures against this bug.

**Comment by masasam** [comment]
Hi @gour .
Please erase the test.ad file if it exists.
Since hugo can not distinguish between test.ad and test.adoc, it gets an error.
I will consider countermeasures against this bug.

**Comment by gour** [comment]
> Are you using MELPA?

Yes

> If you are using melpa, please tell me the version of line 7.
Package-Version: 20170425.520?

;; Package-Version: 20170425.520

**Comment by gour** [comment]
Masashı Mıyaura <notifications@github.com> writes:

> Hi @gour .
> Please erase the test.ad file if it exists.

There is no test.ad file.

**Comment by masasam** [comment]
Could you show me your init.el.

**Comment by masasam** [comment]
@gour  Could you show me  your init.el.

**Comment by gour** [comment]
@masasam here is the relevant part:

```
(use-package easy-hugo
  :ensure t
  :config
  (setq easy-hugo-basedir "~/prj/hugo/net/")
  (setq easy-hugo-url "https://my.domain.tld")
  ;;(setq easy-hugo-sshdomain "blogdomain")
  (setq easy-hugo-root "/home/gour/prj/hugo/net/")
  (setq easy-hugo-previewtime "300")
  (setq easy-hugo-asciidoc-extension "adoc")
  :bind ("C-c C-e" . easy-hugo)
 )
```

**Comment by masasam** [comment]
Hi @gour .

It worked.  Try this ...

(use-package easy-hugo
  :init
  (setq easy-hugo-basedir "~/prj/hugo/net/")
  (setq easy-hugo-url "https://my.domain.tld")
  (setq easy-hugo-root "/home/gour/prj/hugo/net/")
  (setq easy-hugo-previewtime "300")
  (setq easy-hugo-asciidoc-extension "adoc")
  (setq easy-hugo-default-ext ".adoc")
  :bind ("C-c C-e" . easy-hugo)
  )

**Comment by gour** [comment]
Ahh, the trick is to put setup under

```
:init
```

section instead of 

```
:config
```

Yes, that helps!!
