### ISSUE TITLE
css rights

### ISSUE THREAD

**Issue by obrowny** [masasam/emacs-easy-hugo#21]
First, your package is amazing !
When I push the public directory to the server, (P) everything is created and pushed correctly except that the rights on the CSS directory become drwx------ and only for this directory. The website can't access the css folder.
If I take the public directory generated by easy-hugo and send it with my sftp client, the rights are drwxr-xr-x.
The rights are changing during the upload through the P command.
changing the rights manually makes the website work again correctly.
Thank you.

**Comment by masasam** [comment]
Hi @obrowny .
Thank you for the report.
I will change the data to be published with P command to 755.
And it makes changes to make customization possible for users who do not use 755.
best regards.

**Comment by obrowny** [comment]
Thank you so much, i've updated the package and it works perfectly !
Creating a post is now super fast !
