### ISSUE TITLE
.org header

### ISSUE THREAD

**Issue by obrowny** [masasam/emacs-easy-hugo#22]
When I use .org file to create a post, the header does not follow my default.md file in the archetype folder.
New posts made in .md have all from the default.md and a description tag as well.
Would it be possible to make the new posts follow the default.md suggestions ?

Have had a look at the code and found that it was hard-coded so I have changed it and recompile the package for my need. However, I will need to do that on every update.
Maybe you should add the author and categories entries as most blogs use it.
Thanks
obrow

**Comment by masasam** [comment]
Hi @obrowny .
Thank you for comment.

> New posts made in .md have all from the default.md and a description tag as well.
>Would it be possible to make the new posts follow the default.md suggestions ?

Wait for hugo to be implemented, or I think that there is no choice but to implement it on its own.

>Have had a look at the code and found that it was hard-coded so I have changed it and recompile 
>the package for my need. However, I will need to do that on every update.

I do not use .org so I want the cooperation of people familiar with .org
Thanks.

**Comment by masasam** [comment]
Hi @obrowny .

I investigated now for hugo.
The header of org is implemented in hugo.
Easy-hugo will also update accordingly.

**Comment by cescoferraro** [comment]
@obrowny just create a default.org file with whatever you want and this will work.

**Comment by masasam** [comment]
Hi @obrowny .
Now easy-hugo has been updated.
When hugo 0.25 or higher, .org file correspond to header.
I could do as cescoferraro said.
just create a default.org file with whatever you want.
@cescoferraro Thank you for your help.

**Comment by obrowny** [comment]
I will try as soon as it's on repos.
In fact, I've noticed that with a default.md in the archetype folder :  (yesterday's version)
If I do a hugo new post/test.org (or md), it takes information from that default.md (so it's fine)
If I use easy-hugo and type n and test.org (or md) it takes information from the code in easy-hugo by default and not from the default.md

**Comment by obrowny** [comment]
found it on the repos.
It seems to work perfectly.
Thank you very much for the work.
Be sure I'll advertise your work and show how emacs and easy-hugo can be so efficient.
