### ISSUE TITLE
insert image

### ISSUE THREAD

**Issue by kandros** [masasam/emacs-easy-hugo#23]
Hi, it would be really cool to have a command to insert a photo from a given local path or url

inspired form:
https://github.com/yewton/hugo.el#hugo-put-image

**Comment by masasam** [comment]
Hi @kandros .
It's definitely cool.
I will implement it with a feeling appropriate for easy-hugo.
Thanks for your comment.

**Comment by masasam** [comment]
Hi @kandros .
Easy-hugo-image has  Implemented so please use it.
Best regards.

**Comment by kandros** [comment]
Thank you @masasam,`img` tag insertion from 'images' folder is indeed cool and will use that feature for sure, but what i linked is bit different.

This is the idea.

<img width="406" alt="schermata 2017-08-13 alle 12 36 32" src="https://user-images.githubusercontent.com/4562878/29248901-217f9032-8024-11e7-8025-0fbc937fe899.png">

I think this could be actually very useful and give a good user experience and work well with what you just implemented

Thanks again for easy-hugo 🙏

**Comment by masasam** [comment]
@kandros that's cool !
I've understood your idea.
It's nice flowchart.
Thanks.

**Comment by masasam** [comment]
Hi @kandros .
I has Implemented easy-hugo-pull-image and easy-hugo-put-image.
I divided it into two functions considering ease of use.
This is convenient as you say.
Thank you for your idea.

**Comment by kandros** [comment]
This is going to be really usefull 

Thank you! 

Implemented in https://github.com/masasam/emacs-easy-hugo/commit/f5faebfa59538ab7ff891730574613439fe67fda
