### ISSUE TITLE
preview post under the point

### ISSUE THREAD

**Issue by amosbird** [masasam/emacs-easy-hugo#26]
It would be nice to open url with current post link under the point if there is one.

**Comment by masasam** [comment]
Hi @amosbird .
Thank you for comment.
I don't understand the meaning, so please give me a little more detail.

**Comment by amosbird** [comment]
ok, lemme do a screencast :)

**Comment by amosbird** [comment]
I hope it would make things clear.  https://la.wentropy.com/_YFO.webm

**Comment by masasam** [comment]
Hi @amosbird .
Super thanks this screencast.
I also want that function.
Since you can change the URL with config.toml, URL is not uniquely determined.
The URL is different for each user.
Since hugo does not have this function, I'm worried about making this function with only elisp.
I want to ask opinion.

config.toml
[permalinks]
post = "/:year/:month/:day/:title/"

**Comment by amosbird** [comment]
hmm, sorry but i don't understand. Do you mean we need hugo to provide that functionality? I think we can try with the default path and fallback to the main page if 404 :)

**Comment by masasam** [comment]
Hi @amosbird .
There are hands to try implementing simple ones.
But I think that the most troublesome is the title.
Multilingual compatibility and space handling.
What is your URL like?

**Comment by amosbird** [comment]
ah. It looks like this `https://wentropy.com/post/dictionary/`

**Comment by masasam** [comment]
Sorry @amosbird .
What is your preview URL like?
and
What is your config.toml like?

**Comment by amosbird** [comment]
oh, ok. I'm on my phone now. I'll post them later. Thanks for your quick reply :)

**Comment by masasam** [comment]
Ok @amosbird .
See you later.

**Comment by amosbird** [comment]
preview URL `http://localhost:1313/post/dictionary/`

config.toml

```
baseURL = "https://wentropy.com"
languageCode = "zh-cn"
title = "人体工程码学"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true
```

**Comment by masasam** [comment]
Hi @amosbird .
I see.
I Implement for default users and english url user.
Best regards

**Comment by amosbird** [comment]
Great! Thank you @masasam

**Comment by masasam** [comment]
Hi @amosbird .
I has Implemented preview at the file name on the pointer.
This is useful as you say.
Thanks for a good idea.

**Comment by amosbird** [comment]
Hi @masasam . Thanks for the hard work. I've update to the maste commit but still cannot get the file based preview.

**Comment by amosbird** [comment]
Hi @masasam . Thanks for your hard work!
