### ISSUE TITLE
How about exporting org to markdown in emacs

### ISSUE THREAD

**Issue by amosbird** [masasam/emacs-easy-hugo#28]
Hi, `hugo`'s org support is quite fragile. It doesn't export source code blocks or tables correctly. I wonder if we can automatically convert org to markdown and use that as `hugo`'s input file.

**Comment by masasam** [comment]
Hi @amosbird .
I am not familiar with org,
Have you tried ox-hugo (See https://github.com/kaushalmodi/ox-hugo)?

**Comment by amosbird** [comment]
Ah, thanks! I'll try it out.

**Comment by cescoferraro** [comment]
@amosbird I am exporting source code blocks and tables correctly with hugo.
www.cescoferraro.xyz
