### ISSUE TITLE
Error: Did you execute hugo new site bookshelf?

### ISSUE THREAD

**Issue by Sbozzolo** [masasam/emacs-easy-hugo#29]
Hello,

I believe that the error message: `Did you execute hugo new site bookshelf?` is misleading, it took me a while to figure out that I had just mistyped the variable `easy-hugo-basedir`. The error pops out when the folder `easy-hugo-basedir + content/posts` doesn't exist, and I think that this should be the content of the error message.

Bye,
Sbozzolo

**Comment by masasam** [comment]
Hi @Sbozzolo .
Thank you for comment.
Indeed it is true.
I will Correct the error message.

**Comment by Sbozzolo** [comment]
Hi, 
I won't open another issue for just a typo, but the docstring for `easy-hugo-postdir` should be corrected with:
`Directory where the theme stores its posts.` 

The same for the docstring `Number of your blog which you managed.`, I would suggest to correct with:
`Number of blogs you want to manage.`

Regards,
sbozzolo

**Comment by masasam** [comment]
@Sbozzolo Thank you for proposal.
I fix it.
