### ISSUE TITLE
Single blog many folders

### ISSUE THREAD

**Issue by Sbozzolo** [masasam/emacs-easy-hugo#30]
Hello,

I would like to use easy-hugo to manage my academic website, which is based on the academic hugo theme (https://github.com/gcushen/hugo-academic). In this theme there are many folders that contain content, ie one for posts, one for talks, and so on. Is there a way to manage this structure with easy-hugo?

I thought I could define many blogs with different postdirs. This requires a little tweaking in the source code but it is easily doable. Nonethless, I don't think it is a sleek solution. It would be nice if easy-hugo implemented directly the capability of switching post folder as it already does with swtiching blogs.

With regards,
sbozzolo

**Comment by cescoferraro** [comment]
@Sbozzolo same thing here! 
I workaround this by setting multiple identical blog with different postdir/, but still far from ideal.

**Comment by masasam** [comment]
Hi @Sbozzolo . 
Hi @cescoferraro  .
Thank you for comment.
I did not know the theme of using a lot of folders.
It can be done by cescoferraro's method, but it is far from ideal.
How about changing the folder by pressing + or - on easy-hugo screen as an idea to be implemented from now on?

**Comment by cescoferraro** [comment]
@masasam https://github.com/nishanths/cocoa-hugo-theme here its a hugo theme with multiple folders. 
I use this at my portifolio.

**Comment by masasam** [comment]
@cescoferraro Cocoa-hugo-theme seems to be good if you can switch folders directly under easy-hugo-basedir/content.
How about that?

**Comment by cescoferraro** [comment]
sounds good

**Comment by masasam** [comment]
Hi @Sbozzolo @cescoferraro .

I have implemented easy-hugo-next-postdir and easy-hugo-previous-postdir.
By default launching with content/post.
You can move with , or . key
It is not necessary to set easy-hugo-postdir.
Best regards.

**Comment by Sbozzolo** [comment]
Hello,

I've finally tested the feature and it works like a charm!
Just one thing: I don't have the folder `content/post`, but `easy-hugo` always assumes I should have it and prompts errors every now and there, for example switching among the postdirs. This is beacuse `content/post` is explicitly used in `easy-hugo-next-postdir` and `easy-hugo-previous-postdir`. Wouldn't it be better to use the default postdir of the current blog in that functions instead of `content/post`? This would avoid the aforementioned errors.

Best

**Comment by masasam** [comment]
Hi @Sbozzolo .

Thank you for test.
When there is no content/posts folder,
(setq easy-hugo-postdir "content/home")
Fixed the bug so that it works with this.
I will implement this function for multiple blogs in the future
Best regards
