### ISSUE TITLE
org-header not used when executing easy-hugo-newpost

### ISSUE THREAD

**Issue by nickanderson** [masasam/emacs-easy-hugo#33]
I am running in spacemacs and it seems to really break easy-hugo so I am not using that main menu yet.

I am running hugo 0.31 and I use .org as the default file extension. easy-hugo-newpost does initialize a new post but it does not use the org header.

**Comment by masasam** [comment]
Hi @nickanderson .
Have you this file?

archetypes/default.org
+++
categories = [""]
tags = [""]
title = "{{ replace .TranslationBaseName "-" " " | title }}"
date = "{{ .Date }}"
draft = false
+++

https://github.com/masasam/PPAP/blob/master/archetypes/default.org

**Comment by nickanderson** [comment]
No, I do not. I interpreted the elisp that it would inject the org style header. However, creating the file with org syntax does result in the desired behaviour.

```
#+Title: "{{ replace .TranslationBaseName "-" " " | title }}"
#+DATE: "{{ .Date }}" 
#+TAGS: [""]
#+DRAFT: false

```

**Comment by nickanderson** [comment]
Thanks!

**Comment by masasam** [comment]
Hi @nickanderson .
You can use with the following settings at https://github.com/masasam/emacs-easy-hugo/commit/25e4f9dae0d744e1ee23c7a45292ba1d38137917
(setq easy-hugo-org-header t)

**Comment by nickanderson** [comment]
Ah, great thanks!
