### ISSUE TITLE
Please add support spacemacs

### ISSUE THREAD

**Issue by bimawa** [masasam/emacs-easy-hugo#35]
Now hotkeys not work, i think its need binds.

**Comment by masasam** [comment]
Hi @bimawa .
Thank you for comment.
Since I'm not using spacemacs, please explain in a bit more detail.

**Comment by bimawa** [comment]
i need research a problem, but now hotkeys not work. :(

**Comment by masasam** [comment]
Hi @bimawa .
Does it mean that the space key can not be used with easy-hugo-mode?

**Comment by bimawa** [comment]
hi @masasam.
Not only space, <kbd>n</kbd>,<kbd>p</kbd>,<kbd>v</kbd>... its buttons related with evil mode, i think it conflict with easy-hugo. But <kbd>R</kbd> working.
I create cross issue in spacemacs repo. Mb guys from it help to us.

**Comment by masasam** [comment]
Hi @bimawa .
Please let me know because I can not verify without creating the same environment as you.

**Comment by bimawa** [comment]
Yea ok. I'll research it.

**Comment by masasam** [comment]
Hi @bimawa .
There was a person using easy-hugo with spacemacs.
http://www.cmdln.org/2017/11/25/dot-spacemacs/

**Comment by bimawa** [comment]
wow thanks 

Hi @nickanderson, can you tell to us, how are you use it in spacemacs? You rebind all keys? Or create a new Layout for spacemacs?

**Comment by masasam** [comment]
@bimawa Have you try move easy-hugo in the initial state of spacemacs?

**Comment by masasam** [comment]
I know nickanderson, but he does not say easy-hugo does not work on spacemacs.
I close this issue.
@bimawa Please also delete the issue of spacemacs https://github.com/syl20bnr/spacemacs/issues/10204.
Since open source developers are busy, they should not be used privately.
If you want to use emacs, let's do the setup yourself.
It is manners to issue an issue after confirming that it is a bug.

**Comment by bimawa** [comment]
I think develop layer for easy-hugo for spacemacs. 

>Have you try move easy-hugo in the initial state of spaceemacs

Yes like in docs described. It's not first my configuration. I think I do all correct.

**Comment by masasam** [comment]
@bimawa .
I installed and run spacemacs.
There is some evil-mode and key binding in spacemacs.
Evil-mode and easy-hugo key bindings collide.
If you turn evil-mode off, easy-hugo can work.
Are you ordering me to make it work on evil-mode?

**Comment by masasam** [comment]
@bimawa You can set key bindings that don't conflict with evil-mode.
Why should I do it?

**Comment by nickanderson** [comment]
Hi @bimawa,

I do use easy-hugo with spacemacs. However it's pretty rough. It messes up key bindings so after I am done I usually restart emacs to fix my keybings until the next time I use it.

I currently only use it by invoking easy-hugo-newpost and easy-hugo-publish directly.

**Comment by bimawa** [comment]
Yeah guys its work if disable evil-mode, just press <kbd>CTRL-Z</kbd> and all keys work. 
Thanks a lot for help! But I'll think about layer ) maybe i can do layout for spacemacs.

>Are you ordering me to make it work on evil-mode?

No no, just search a point where i can contribute it )

**Comment by masasam** [comment]
@bimawa You can contribute by opening easy-hugo working setting in evil-mode and spacemacs to github.
I think this is a very good thing.
@nickanderson Thank you for your help.

**Comment by bimawa** [comment]
Yes, thanks a lot @masasam, I'll try. Just love emacs very hard. @nickanderson thanks for your time.

**Comment by cescoferraro** [comment]
Maxim! Check my dotfiles. I use this with evil-mode not Spacemacs, but your
problem it’s most likely to be on the evil side. I am commuting, but it
won’t be that hard to spot the specific bindings you need.

**Comment by nickanderson** [comment]
https://github.com/cescoferraro/dotfiles/blob/master/src/emacs.d/configuration.org#hugo

**Comment by masasam** [comment]
@bimawa Does your problem solve at https://github.com/masasam/emacs-easy-hugo/issues/35#issuecomment-359630563 ?
@cescoferraro @nickanderson Thanks to cool reply.

**Comment by bimawa** [comment]
@cescoferraro @masasam @nickanderson Guys yes that work! Thanks a lot! Love you!

**Comment by masasam** [comment]
I am going to add this at README for evil-mode and spacemacs user.
Thanks all help.

**Comment by cescoferraro** [comment]
The library is amazing it deserves a spacemacs layer.

**Comment by bimawa** [comment]
>The library is amazing it deserves a spacemacs layer.

yes i think same

**Comment by mandarvaze** [comment]
@masasam Do you need help with updating the README ?

I just installed `easy-hugo`. I use spacemacs.  Let me read the links and try it myself. If I am successful, I may be able to update README for spacemacs.

**Comment by yssource** [comment]
please support spacemacs :+1:
