### ISSUE TITLE
Publish time for displaying posts

### ISSUE THREAD

**Issue by balaramadurai** [masasam/emacs-easy-hugo#39]
@masasam ,
  Thank you for your work with easy-hugo. It has really made working with hugo and org-mode a breeze. 

I would like to find out if there is an option to sort the order of the published posts with the date of publishing rather than file creation/modification date? 

If it is not there currently, can I please request you to treat this as a feature request?

Thanks again for the exemplary work
Bala

**Comment by masasam** [comment]
Hi @balaramadurai .
Thank you for comment.

I think it is a very good idea.
I want option to sort the order of the published posts with the date of publishing.

**Comment by masasam** [comment]
Hi @balaramadurai .
I've implemented easy-hugo-sort-publishday.
Please use it.

It is convenient because it is possible to sort by date of publishing.
I appreciate your nice idea.

**Comment by balaramadurai** [comment]
Hi @masasam,
 Thank you so much implementing the idea so quickly. I have started using it and it's amazing!

Thanks and have a great day!
Bala
