### ISSUE TITLE
Using `require` is better to check `helm-ag` or `counsel` installed or not

### ISSUE THREAD

**Issue by SuzumiyaAoba** [masasam/emacs-easy-hugo#43]
Now using `package-installed-p` but it can support users who install packages via `package.el`.

https://github.com/masasam/emacs-easy-hugo/blob/3b0516c87d33a75dd777f6336fdf53be0374abcb/easy-hugo.el#L1163-L1167

This doesn't support those who use `Cask`, `el-get`, etc.
Is it better to use `require` instead of `package-installed-p`?

```emacs-lisp
(defun easy-hugo-ag ()
  "Search for blog article with counsel-ag or helm-ag."
  (interactive)
  (easy-hugo-with-env
   (if (require 'counsel nil t)
       (counsel-ag nil (expand-file-name easy-hugo-postdir easy-hugo-basedir))
     (if (require 'helm-ag nil t)
	 (helm-ag (expand-file-name easy-hugo-postdir easy-hugo-basedir))
         (error "'counsel' or 'helm-ag' is not installed")))))
```

**Comment by masasam** [comment]
Hi @SuzumiyaAoba .
Thank you for comment.

> This doesn't support those who use Cask, el-get, etc.
Is it better to use require instead of package-installed-p?

You're right.
I 've fixed it at https://github.com/masasam/emacs-easy-hugo/commit/e0bbe40c99c4ab2c59b00f98b1e1c903561936af.
Thank you for your advice.

**Comment by SuzumiyaAoba** [comment]
Thanks for your swift response.

It works for me, but new problem appears.
If I installed both `counsel` and `helm-ag` then it is forced to use `counsel-ag`
(I mainly use `helm-ag`, but `counsel` is also installed because some packages seem like depending on `counsel`).
So this package should provide the option of using `helm-ag` or `counsel`.

**Comment by masasam** [comment]
Hi @SuzumiyaAoba .
Make helm-ag and counsel-ag selectable at https://github.com/masasam/emacs-easy-hugo/commit/8bf48b973905c4ab488633226b3dfb3317d8c745 .

You can use helm-ag by writing the following to .emacs or init.el

    (setq easy-hugo-helm-ag t)

**Comment by SuzumiyaAoba** [comment]
Thanks for your work!

This package is more useful :tada:
