### ISSUE TITLE
Github deploy bug

### ISSUE THREAD

**Issue by balaramadurai** [masasam/emacs-easy-hugo#44]
Hello @masasam,
  I absolutely love the ease of using easy-hugo. I, now, use your package with 4 hugo based websites :smile: . Thanks for your hard work.

I never tried using the Github deploy, but recently, I felt like experimenting with it. But when I tried, the entire path had a space in it and the error I got was always `No such file or directory... <mypath>/deploy.sh`

Recently, I found out that when the path did not have a space in it, then it worked fine. 

Example, my path had the folder by name `Our Websites`. I renamed this to `Websites` and it started working fine.

Thanks and have a good day!
Bala

**Comment by masasam** [comment]
Hi @balaramadurai .
Thank you for comment.
I've fixed bug in directory containing space at https://github.com/masasam/emacs-easy-hugo/commit/bcebd371b70a592d1a74169de91b6102e06265a3 .
I appreciate your report.
