### ISSUE TITLE
Change postdir of a specific blog

### ISSUE THREAD

**Issue by minorugh** [masasam/emacs-easy-hugo#46]
I'm using emacs-easy-hugo with multiple blog,
and postdir setting is used by default.

However, I'd like to change postdir setting for specific one blog.
Give me a hint on how to deal with it.

**Comment by masasam** [comment]
Hi @minorugh .
Thank you for comment.

The following is the setting you want.

    (setq easy-hugo-basedir "~/src/mainblog/")
    (setq easy-hugo-url "https://yourmainblog")
    (setq easy-hugo-sshdomain "blogdomain")
    (setq easy-hugo-root "/home/mainblog/")
    (setq easy-hugo-bloglist '(((easy-hugo-basedir . "~/src/blog2/")
			    (easy-hugo-url . "https://yourblog2domain")
			    (easy-hugo-postdir . "content/blog")
			    (easy-hugo-sshdomain . "blogdomain2")
			    (easy-hugo-root . "/home/blog2/"))))

Hope this helps.

**Comment by minorugh** [comment]
Hi @masasam.
Thank you for advice.

I tried that setting already.
The article list correctly "content/blog" It will be changed.
However, When 'new-post' is executed, it's added to "content/post" instead of "content/blog".

**Comment by masasam** [comment]
Hi @minorugh .
Your customized function is running instead of easy-hugo standard function.
See https://github.com/minorugh/emacs.d/blob/master/inits/80_easy-hugo.el#L75-L93

Hope this helps.

**Comment by minorugh** [comment]
Sorry @masasam .
Just now I also noticed there was a problem with my settings.
I will check my settings again and report correctly.

Thanks.

**Comment by minorugh** [comment]
@masasam.

After comment out my custmized function it worked fine.
Sorry to trouble you. really sorry.
My customization function can be solved by devising template.

I,m sorry for a childish follower, please help me without abandoning.
Thank you so much.

**Comment by masasam** [comment]
Hi @minorugh .

Mistakes are not ashamed.
Because sharing the source code with everyone is to cooperate with ideas and bug fixes.
