### ISSUE TITLE
Emacs hangs after running easy-hugo-newpost

### ISSUE THREAD

**Issue by jackbaty** [masasam/emacs-easy-hugo#47]
I'm not sure when this started, but when calling `easy-hugo-newpost` (20181022.833 in Emacs 26.1.1) hangs, requiring me to force quit (macOS).  Steps:

1. Start easy-hugo
2. Run `easy-hugo-newpost`
3. Type a filename (e.g. myfile.md)
4. Hit return

At this point, Emacs (gui, macOS) becomes unresponsive. The new file is created correctly, though. Not sure how to help debug this, but let me know if there's anything I can do.

Jack

**Comment by masasam** [comment]
Hi @jackbaty .
Thanks for report.
I often hear that emacs doesn't work with macOS Mojave.
See https://github.com/railwaycat/homebrew-emacsmacport/issues/141 or https://www.reddit.com/r/emacs/comments/99lo51/emacs_and_mojave/.
I think that it will be settled by examining this.
But I don't use macOS so I am not familiar with it.

**Comment by jackbaty** [comment]
Thanks, I'll look into possible Mojave issues. I thought most of them had been resolved but looks like there's at least one more :). I'll let you know if I find anything useful.

**Comment by jackbaty** [comment]
I think I've finally figured out what caused the hang. At some point I had put the following in my config.toml

`newContentEditor = "vim"`

I'm guessing Emacs didn't like that much :)

Removing that line fixes the hang.

**Comment by masasam** [comment]
Hi @jackbaty 
I am glad that the problem was solved.
Thanks for the report.
