### ISSUE TITLE
rsync (command does not end normally)

### ISSUE THREAD

**Issue by obrowny** [masasam/emacs-easy-hugo#53]
Thank you very much for easy-hugo it is a pleasure to use it !

hugo version : 0.69.2
emacs version: 26.3
orgmode version: 9.3.6

When pushing the blog, everything seems to work perfectly but I get an error report with rsync.

```
Debugger entered--Lisp error: (error "’rsync’ command does not end normally")
  signal(error ("’rsync’ command does not end normally"))
  error("'rsync' command does not end normally")
  easy-hugo-publish()
  easy-hugo-publish-clever()
  funcall-interactively(easy-hugo-publish-clever)
  #<subr call-interactively>(easy-hugo-publish-clever nil nil)
  apply(#<subr call-interactively> easy-hugo-publish-clever (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> easy-hugo-publish-clever nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (easy-hugo-publish-clever nil nil))
  call-interactively(easy-hugo-publish-clever nil nil)
  command-execute(easy-hugo-publish-clever)
```
I don't know if it is related to easy-hugo or not. It is unclear for me so I am just asking if you could help with that.

Thank you.

**Comment by masasam** [comment]
Hi @obrowny .
Thank you for comment.
Please write your emacs settings here.

**Comment by obrowny** [comment]
Here is my config :


(require 'helm-ag)
(setq easy-hugo-helm-ag t)
(setq easy-hugo-server-flags "-D")
(setq easy-hugo-image-directory "images/")
(setq easy-hugo-default-picture-directory "static/images/")
(setq easy-hugo-default-ext ".org")
(setq easy-hugo-basedir "~/site/blog/")
(setq easy-hugo-url "https://blog.domain.org/")
(setq easy-hugo-sshdomain "myssh")
(setq easy-hugo-root "/home/company/www/blog/")
(setq easy-hugo-previewtime "300")
(define-key global-map (kbd "C-c h") 'easy-hugo)

Thank you.

Мasashi Мiyaura <notifications@github.com> writes:

> Hi @obrowny .
> Thank you for comment.
> Please write your emacs settings here.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Obrow
Emacs 26.3

**Comment by masasam** [comment]
Please check if rsync is installed on server and desktop.
Please check if ~ / .ssh / config looks like follows

    Host myssh
			HostName {your-server-ip-address}
			User {your-ssh-user-name}

If this doesn't fix, try it that you are going to install [keychain-environment](https://github.com/tarsius/keychain-environment).

**Comment by obrowny** [comment]
rsync is installed on desktop and should be on server (web hosting) as it was working few days ago.
ssh config is fine.
Maybe the problem comes from webhosting. (ovh)
I've just upgraded from hugo 0.53 to 0.69.3 and I wanted your expertise about it.
Nevertheless, it works well and the blog is working fine. 
Thank you

**Comment by obrowny** [comment]
I've tried with keychain-environment with no success.

I haven't shared another message that may help.

```
Time value of . truncated on receiver.
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

**Comment by masasam** [comment]
@obrowny I've added the ability at https://github.com/masasam/emacs-easy-hugo/commit/9e923e32f21134bb89196a169f5a3f2aecfe45cb to change rsync options.
It will be reflected in melpa after about 6 hours.

After updating easy-hugo try the following at your init.el.

     (setq easy-hugo-rsync-flags "-rlOtcv")

**Comment by obrowny** [comment]
ok I will try it and get back to you.
Thank you very much
ありがとう ございます

**Comment by obrowny** [comment]
I have received the upgrade and get the same error.

```
sending incremental file list
Time value of . truncated on receiver.

sent 19,415 bytes  received 462 bytes  13,251.33 bytes/sec
total size is 107,809,509  speedup is 5,423.83
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

**Comment by masasam** [comment]
Have you tried deleting all the files you uploaded to the server and trying again?
If there are files that cannot be deleted on the server, I think it's a good idea to change the following.

     (setq easy-hugo-root "/home/company/www/blogtest/")

**Comment by obrowny** [comment]
Yes I've tried to delete both local public directory and remote blog directory and create a new empty remote directory with no success.
I've tried to downgrade web hosting php stack (just in case) but with no success either.
It may be a problem from the hoster and not from your package.

**Comment by masasam** [comment]
Both my laptop and server's rsync version are 3.1.3 but I had no problem.

    rsync --version
    rsync  version 3.1.3  protocol version 31

**Comment by obrowny** [comment]
```
rsync --version
rsync  version 3.1.2  protocol version 31
```
I may upgrade my system in few weeks and let you know if things get better.
Nevertheless, things work well despite the error message. The blog is online with everything. it is just that 2 weeks ago it was working perfectly.
Thank you for your time.
