### ISSUE TITLE
I cannot understand the documentation at all

### ISSUE THREAD

**Issue by alienbogart** [masasam/emacs-easy-hugo#55]
This is a very general comment, but I used a similar package, Org2Blog, and it was not hard to understand it with some effort. `emacs-easy-hugo` may truly be easy, but I have no idea how to interpret large portions of the documentation. There are no actual examples, and I might need to devote a lot of time of mindless guesswork just to make it work. The idea is good, but the lack of organized documentation makes me think that I would be better suited by writing straight to markdown and using the command line.

If you really want more people to use this, I suggest you spend more time with the documentation and less time coding - at least for a while.

At this point, I'm giving up.

Thanks anyway.

**Comment by masasam** [comment]
@mrbig033 I can't answer unless you specifically point out what you don't understand.
