### ISSUE TITLE
Any plans for `completion-at-point` for categories and tags?

### ISSUE THREAD

**Issue by c-alpha** [masasam/emacs-easy-hugo#68]

**Comment by masasam** [comment]
We are waiting for a pull request.
If there is something that does not adversely affect the existing implementation and user's environment, I'll merge it.

**Comment by c-alpha** [comment]
To use `completion-at-point` (CAPF for short), `easy-hugo`'s CAPF function will need to determine whether point is in a context where a tag or category is wanted, and return completion candidates in that case only.

Looking at the matrix of front matter formats (tonl, yaml, json, org) vs. content formats (markdown, org, asciidoc, rst, html), this seems more work than it's worth for me at the moment.

Sorry for not having better news at this point.
