### ISSUE TITLE
it's conflict to evil-mode

### ISSUE THREAD

**Issue by wow-yorick** [masasam/emacs-easy-hugo#70]
when i use evil mode enter  easy-hugo mode, easy-hugo's key map is invalid

**Comment by masasam** [comment]
Hi @wow-yorick .
Thank you for comment.
Have you tried [spacemacs-easy-hugo](https://github.com/humanfactors/spacemacs-easy-hugo)?

**Comment by wow-yorick** [comment]
i use  https://github.com/seagle0128/.emacs.d

**Comment by wow-yorick** [comment]
oh,oh...  i get it, thanks

**Comment by wow-yorick** [comment]
solved

**Comment by pace577** [comment]
@wow-yorick I had the same problem and I'm using Doom Emacs. How did you solve it?
I added the following line to the `:config` of my `use-package` block (saw that line in spacemacs-easy-hugo repo) and it seems to work fine without the `easy-hugo-menu`. But the `k` key still doesn't work in `easy-hugo-menu`.
``` emacs-lisp
(evil-make-overriding-map easy-hugo-mode-map 'normal)
```
