### ISSUE TITLE
`easy-hugo-previous-line` doesn't work with `easy-hugo-enable-menu`

### ISSUE THREAD

**Issue by pace577** [masasam/emacs-easy-hugo#71]
When the transient menu style is enabled with `easy-hugo-enable-menu`, pressing `k`  or `C-p` or `<up>` doesn't move the point up. Point movements in other directions seem to work fine.

**Comment by masasam** [comment]
Hi @pace577 !
Thank you for comment.
It works in my environment with the following settings.

```
(setq easy-hugo-no-help t)
(easy-hugo-enable-menu)
```

**Comment by pace577** [comment]
Thanks for the prompt reply @masasam!
I have the same line in my `:config` of my `use-package` block, and the `easy-hugo-no-help` variable is set to `t` already. However, the issue is still there.
Although, if I set the `easy-hugo-no-help` variable to `nil` and set it back to `t` while in the easy-hugo buffer, everything starts working fine.
I am using Doom Emacs, could that be causing the issue somehow?

**Comment by masasam** [comment]
Please give it a try to write the settings in your :init of your use-package block instead of :config.
I hope this will work.
