### ISSUE TITLE
deploy.sh?

### ISSUE THREAD

**Issue by summeremacs** [masasam/emacs-easy-hugo#75]
Hi,
I'm stumped about the deploy.sh part. The link about the password thing goes to a really old post. Plus, is it even deploy.sh anymore? Cuz I set mine up with .github/workflows/hugo.yaml ? As it says in https://gohugo.io/hosting-and-deployment/hosting-on-github/

So my question is: what do I do for deploy.sh? Is there a config I can copy/paste/edit? I'm really confused. I want to use easy-hugo because then I can write in org-mode instead of markdown. But it won't deploy at all so I don't know what to do.

Thx for any help.

**Comment by masasam** [comment]
Hi @summeremacs !
Thank you for comment.
If you use .github/workflows/hugo.yaml, GitHub Actions will work, so you don't need deploy.sh.

**Comment by summeremacs** [comment]
Thanks! But when I hit "G" for github deploy in easy-hugo, I get the following message in the minibuffer (and it doesn't deploy):

`easy-hugo-github-deploy: /Users/summer/Documents/site/summeremacs/deploy.sh do not execute`

**Comment by masasam** [comment]
Since you use GitHub Actions, I think that it will be deployed if you commit with "M" (magit) instead of "G".

**Comment by summeremacs** [comment]
TYSM! It works! 🙃 TY again. 😀
