### ISSUE TITLE
Rendered Checkboxes?

### ISSUE THREAD

**Issue by summeremacs** [masasam/emacs-easy-hugo#76]
Hi again, I'm sorry to bother you once more.
I'm trying to get org-mode checkboxes to render on my site, but they aren't. Instead of checkboxes at the start of every list item, they come out as little dots when they are exported. I'm not sure if that's easy-hugo's exporter or something else?

Please let me know if I'm doing something wrong? I'm just exporting an org-mode list of movies I've watched but the checkboxes definitely aren't exporting like they would from org-mode.

Thanks! Sorry again for the bother.

**Comment by masasam** [comment]
Hi again!
Easy-hugo has no ability to export org-mode checkboxes.
I think it's probably because hugo doesn't implement the ability to export org-mode checkboxes.

**Comment by summeremacs** [comment]
Thanks for the reply! I *just* found out how to do it though with ox-hugo. Basically I export my file to .md and it will render the checkboxes. It's a bit convoluted, but since I don't use checkboxes all that often, it's not too bad at all. I just need to add some #+ stuff at the top so the exporter knows how to do it and then I just upload the resulting .md file. 🙃

As you can see here: https://summeremacs.github.io/posts/60s-70s-80s-watch-list/

It definitely works. So the workaround is pretty easy. Write the list in org, use ox-hugo to export to .md, and then upload the .md file with easy-hugo as normal and it should be fine. 🙃

ty again for the replies!
